# Generated by Django 5.0.3 on 2024-03-20 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_bussiness',
            new_name='is_business',
        ),
    ]
