# github actions CI/CD
---
name: Checks # workflow 이름
# git push 때마다 체크
on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout # 깃험 레포에 있는 코드를 작업환경으로 가져오는 역할
        uses: actions/checkout@v2
      - name: Test # 테스트 코드 실행
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint # flake8을 이용한 pep8 파이썬 코드 스타일 가이드 준수 여부 검사
        run: docker-compose run --rm app sh -c "flake8"